# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PycharmProjects/MRC/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QLabel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 666)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setGeometry(QtCore.QRect(980, 80, 41, 31))
        self.searchBtn.setObjectName("searchBtn")
        self.category = QtWidgets.QComboBox(self.centralwidget)
        self.category.setGeometry(QtCore.QRect(810, 40, 211, 40))
        self.category.setObjectName("category")
        self.category.addItem("")
        self.category.addItem("")
        self.category.addItem("")
        self.category.addItem("")
        self.category.addItem("")
        self.category.addItem("")
        self.category.addItem("")
        self.category.addItem("")
        self.searchtext = QtWidgets.QLineEdit(self.centralwidget)
        self.searchtext.setGeometry(QtCore.QRect(810, 80, 161, 31))
        self.searchtext.setObjectName("searchtext")
        self.reduncheck_window = QtWidgets.QPushButton(self.centralwidget)
        self.reduncheck_window.setGeometry(QtCore.QRect(810, 500, 201, 61))
        self.reduncheck_window.setObjectName("reduncheck_window")
        self.create_window = QtWidgets.QPushButton(self.centralwidget)
        self.create_window.setGeometry(QtCore.QRect(810, 430, 201, 61))
        self.create_window.setObjectName("create_window")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 570, 369, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.horizontalLayout.addWidget(QLabel("1 ..."))

        self.prevBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.prevBtn.setObjectName("prevBtn")
        self.horizontalLayout.addWidget(self.prevBtn)
        self.currentPage = QtWidgets.QLabel(self.layoutWidget)
        self.currentPage.setObjectName("currentPage")
        self.horizontalLayout.addWidget(self.currentPage)
        self.nextBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalLayout.addWidget(self.nextBtn)
        self.max_page = QtWidgets.QLabel(self.layoutWidget)
        self.max_page.setObjectName("max_page")
        self.horizontalLayout.addWidget(self.max_page)
        self.pageEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.pageEdit.setObjectName("pageEdit")
        self.horizontalLayout.addWidget(self.pageEdit)
        self.switchBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.switchBtn.setObjectName("switchBtn")
        self.horizontalLayout.addWidget(self.switchBtn)

        self.data_table = QtWidgets.QTableWidget(self.centralwidget)
        self.data_table.setGeometry(QtCore.QRect(10, 40, 791, 531))
        self.data_table.setObjectName("data_table")
        self.data_table.setColumnCount(0)
        self.data_table.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.toolbar = QtWidgets.QToolBar(MainWindow)
        self.toolbar.setGeometry(QtCore.QRect(0, 0, 1033, 30))
        self.toolbar.setObjectName("toolbar")
        self.toolbar.setIconSize(QtCore.QSize(25, 25))
        self.loadAction = QAction('load', self.toolbar)
        self.loadAction.setIcon(QIcon("./icon/load.png"))
        self.saveAction = QAction('save', self.toolbar)
        self.saveAction.setIcon(QIcon("./icon/save.png"))
        self.saveAction.setShortcut('Ctrl+S')
        self.refreshAction = QAction('refresh', self.toolbar)
        self.refreshAction.setIcon(QIcon("./icon/refresh.png"))
        self.refreshAction.setShortcut('Ctrl+Shift+R')
        self.toolbar.addAction(self.loadAction)
        self.toolbar.addAction(self.saveAction)
        self.toolbar.addAction(self.refreshAction)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchBtn.setText(_translate("MainWindow", "검색"))
        self.category.setItemText(0, _translate("MainWindow", "카테고리별 찾기"))
        self.category.setItemText(1, _translate("MainWindow", "한식"))
        self.category.setItemText(2, _translate("MainWindow", "양식"))
        self.category.setItemText(3, _translate("MainWindow", "일식"))
        self.category.setItemText(4, _translate("MainWindow", "중식"))
        self.category.setItemText(5, _translate("MainWindow", "분식"))
        self.category.setItemText(6, _translate("MainWindow", "치킨"))
        self.category.setItemText(7, _translate("MainWindow", "피자"))
        self.reduncheck_window.setText(_translate("MainWindow", "중복 검사"))
        self.create_window.setText(_translate("MainWindow", "대화 데이터 추가"))

        self.prevBtn.setText(_translate("MainWindow", "<<"))
        self.max_page.setText(_translate("MainWindow", "max"))
        self.nextBtn.setText(_translate("MainWindow", ">>"))
        self.currentPage.setText(_translate("MainWindow", "current"))
        self.switchBtn.setText(_translate("MainWindow", "이동"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
